### ISSUE TITLE
question:

### ISSUE THREAD

**Issue by Zibri** [siwiembedded/tool-pysiwiflasher#2]
I have an MT6261 device (a mini phone).

It has 4MB of flash, which I dumped.

I wish to write it back but not just the firmware, all of it...
Looking at your code it should be possible.
Any idea how?

**Comment by ajaybhargav** [comment]
you need to convert dump file to firmware first. Use the readback extractor tool from here:
https://forum.xda-developers.com/t/universal-readback-extractor-for-mtk-feature-watchphones.3289272/

I would suggest you use flashtool instead of this flasher. It does not flash bootloader which is required in your case. All the required tools are available on the link above.

**Comment by kuzalex2010** [comment]
Hi
I need help. 
I converted dump file to firmware. And I want to write it to another mt6261. But Flashtool say that i try rewrite secure MAUI with un-secure. How can i bypass that? How can I secure my main_maui or un-secure it at mt6261? 
I made dump file from secure mt6261. Then made scater file. And Flashtool allowed to write secure main_Maui to secure mt6261.
Do you have any ideas?
Thank you.
